apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e8adhfevu-python 
  janus-idp.io/tekton: e8adhfevu-python
  backstage.io/kubernetes-id: e8adhfevu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e8adhfevu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  