apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: e8adhfevu-python-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/e8adhfevu-python-gitops